on: push
name: Publicar components para npm
env:
  PUBLISH_TOKEN:  ${{ secrets.token }}
jobs:
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      
      - name: Instalando dependencias
        run: npm install

      - name: Build
        run: npm run build
      
      # Copia arquivos necessários para a pasta dist
      - name: Preparar dist
        run: |
          cp lib-package.json dist/package.json
          cp README.md dist/README.md

      - name: Verificar dist
        run: ls -la dist

      - name: Publicando
        run: npm publish --access public
        working-directory: dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
